#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

leftwm-command "UnloadTheme"

pkill picom
pkill polybar
pkill dunst

#remove desire.conf symlink and, remove appended text
cd $HOME/.config/kitty/
rm desire.conf
sed -i '/desire.conf/d' kitty.conf
cd $SCRIPTPATH

kill $(ps aux | grep "layout.sh" | grep -v grep | awk '{print $2}')
