#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi

ln -s ${SCRIPTPATH}/down /tmp/leftwm-theme-down

#boot compton or picom if it exists
if [ -x "$(command -v picom)" ]; then
  picom &> /dev/null &
fi

#set the theme.toml config
leftwm-command "LoadTheme $SCRIPTPATH/theme.toml"

#set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-fill --randomize /wallpapers/
fi

# extra utils to make this theme a little more homey
if [ -x "$(command -v dunst)" ]; then
  dunst -config ~/.config/dunst/dunstrc &
fi

#include desire.conf to kitty file, and make a symlink.
ln -s kitty/desire.conf $HOME/.config/kitty
echo "include ./desire.conf" >> kitty.conf

#boot a polybar for each monitor
cd ${SCRIPTPATH}/polybar
polybar -m | sed s/:.*// | tac | while read -r monitor
do
  monitor=$monitor polybar -c config.ini main &> /tmp/polybar.log &
done

